stages:
- name: Build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn clean install
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: springboot_docker:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34023
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
